Files updates

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,23 @@
-#!/usr/bin/env bash
-# transfer a file from our client to a server
-if [ $# -lt 3 ];
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
-    exit;
-fi;
+#!/bin/bash
 
-if [ $# -ge 4 ];
-then
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key_path="$4"
+
+# Transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully."
 else
-    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
-fi;
+    echo "Error: File transfer failed."
+fi
